project/coolcad/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

from . import views

urlpatterns = patterns(
    '',
    url(r'^$', views.HomeView.as_view()),
    url(r'^materiais/', include('materiais.urls', namespace="materiais")),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

project/materiais/urls.py
#coding: utf-8

from django.conf.urls import patterns, url

from . import views

urlpatterns = patterns(
    '',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^adicionar_plain/$', views.adicionar_plain, name='adicionar_plain'),
    url(r'^adicionar_class/$', views.adicionar_class, name='adicionar_class'),
    url(r'^adicionar_model/$', views.adicionar_model, name='adicionar_model'),
    url(r'^(?P<material_id>\d+)', views.detalhe, name="detalhe"),
)

project/materiais/models.py
# coding: utf-8

from django.db import models

GRUPO_ALIMENTOS, GRUPO_ALCOOLICOS, GRUPO_NAO_ALCOOLICOS, GRUPO_OUTROS = 1, 2, 3, 4

TIPO_GRUPO_CHOICES = (
    (GRUPO_ALIMENTOS, u'Alimentos'),
    (GRUPO_ALCOOLICOS, u'Alcoólicos'),
    (GRUPO_NAO_ALCOOLICOS, u'Não alcoólicos'),
    (GRUPO_OUTROS, u'Outros'),
)
TIPO_GRUPO_CHOICES_DICT = dict(TIPO_GRUPO_CHOICES)

class GrupoDeMaterial(models.Model):
    nome = models.CharField(max_length=50)
    tipo = models.IntegerField(choices=TIPO_GRUPO_CHOICES, default=GRUPO_OUTROS)

    def __unicode__(self):
        return u"{} - {}".format(self.nome, TIPO_GRUPO_CHOICES_DICT[self.tipo])

class Material(models.Model):
    codigo = models.CharField(u'código', max_length=20)
    descricao = models.CharField(u'descrição', max_length=100)
    unidade = models.CharField(u'unidade', max_length=2)
    grupo = models.ForeignKey(GrupoDeMaterial)

    def __unicode__(self):
        return u"{} - {}".format(self.codigo, self.descricao)

project/materiais/forms.py
#coding: utf-8

from django import forms

from .models import Material, GrupoDeMaterial


class MaterialForm(forms.Form):
    codigo = forms.CharField(label=u'código', max_length=20)
    descricao = forms.CharField(label=u'descrição', max_length=100)
    unidade = forms.CharField(label=u'unidade', max_length=2)
    unidade = forms.CharField(label=u'unidade', max_length=2)
    grupo = forms.ModelChoiceField(
        label=u'grupo',
        queryset=GrupoDeMaterial.objects
    )


class MaterialModelForm(forms.ModelForm):
    class Meta:
        model = Material

project/coolcad/views.py
#coding: utf-8

from django.views.generic import TemplateView

class HomeView(TemplateView):
    template_name = 'coolcad/home.html'

project/materiais/views.py
#coding: utf-8

from django.shortcuts import render
from django.views.generic import ListView

from .models import Material, GrupoDeMaterial
from .forms import MaterialForm, MaterialModelForm


class IndexView(ListView):
    model = Material
    context_object_name = 'materiais'
    template_name = 'materiais/index.html'


def detalhe(request, material_id):
    material = Material.objects.get(pk=int(material_id))
    context = dict(
        material=material
    )
    return render(request, 'materiais/detalhe.html', context)


def adicionar_plain(request):
    grupos = GrupoDeMaterial.objects.all()
    context = dict(
        grupos=grupos
    )
    if request.POST:
        material = Material()
        material.codigo = request.POST['codigo']
        material.descricao = request.POST['descricao']
        material.unidade = request.POST['unidade']
        material.grupo = GrupoDeMaterial.objects.get(pk=request.POST['grupo'])
        material.save()
        context['material'] = material

    return render(request, 'materiais/adicionar_plain.html', context)


def adicionar_class(request):
    context = dict()
    if request.POST:
        form=MaterialForm(request.POST)
        if form.is_valid():
            material = Material()
            material.codigo = form.cleaned_data['codigo']
            material.descricao = form.cleaned_data['descricao']
            material.unidade = form.cleaned_data['unidade']
            material.grupo = form.cleaned_data['grupo']
            material.save()
            context['material'] = material
    else:
        form=MaterialForm()

    context['form'] = form
    return render(request, 'materiais/adicionar_class.html', context)


def adicionar_model(request):
    context = dict()
    if request.POST:
        form = MaterialModelForm(request.POST)
        if form.is_valid():
            context['material'] = form.save()
    else:
        form = MaterialModelForm()

    context['form'] = form
    return render(request, 'materiais/adicionar_class.html', context)

project/templates/_pagination.html
{% if is_paginated %}
<ul class="pagination">
    {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {%else%}
        <li class="disabled"><a href="#">&laquo;</a></li>
    {% endif %}
    {% for page in paginator.page_range %}
        <li {% if page_obj.number == page %}class="active"{% endif %}>
          <a href="?page={{ page }}">{{ page }}</a>
        </li>
    {% endfor %}
    </span>
    {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {%else%}
        <li class="disabled"><a href="#">&raquo;</a></li>
    {% endif %}
</ul>
{% endif %}

project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{%block titulo %}Coolcad{%endblock%}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.css" %}" rel="stylesheet">
    <link href="{% static "css/app.css" %}" rel="stylesheet">
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Coolcad</a>
        <div class="nav-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url "materiais:index" %}">Materiais</a></li>
            <li><a href="#configuracoes">Configurações</a></li>
            <li><a href="#relatorios">Relatórios</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">
    {%block main_content %}
    {%block content %}
      <div>
        <h1>Coolcad - Página principal</h1>
        <p class="lead">Sobrescreva este bloco.</p>
      </div>
    {% endblock content %}
    {% endblock main_content %}
    </div><!-- /.container -->

    {% block "js" %}
    <script type="text/javascript" src="{% static "js/jquery.js" %}"></script>
    <script type="text/javascript" src="{% static "js/bootstrap.js" %}"></script>
    {%endblock%}
  </body>
</html>

project/templates/coolcad/home.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
        <h1>Coolcad</h1>
        <p class="lead">Bem vindo ao cadastro.</p>
        <p><a class="btn btn-lg btn-success" href="{% url "materiais:index"%}">Cadastre alguma coisa</a></p>
</div>
{% endblock content %}

project/templates/materiais/adicionar_class.html
{% extends "materiais/materiais_base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
    {%if material%}
    <div class="alert alert-success">
        Material {{material}} adicionado com sucesso.
    </div>
    {%endif%}
    <h3>Cadastrar material</h3>
    <form action="." method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-default">Enviar</button>
    </form>
</div>
{% endblock content %}

project/templates/materiais/adicionar_plain.html
{% extends "materiais/materiais_base.html" %}

{%block content %}
<div class="row">
    <h3>Cadastrar material</h3>
    {% if material %}
    <div class="alert alert-success">
        Material {{material}} criado com sucesso.
        <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
    {% endif %}

    <form action="{% url "materiais:adicionar_plain"%}" method="POST">
        {% csrf_token %}
        <input type="text" class="form-control" name="codigo" placeholder="Código" /><br />
        <input type="text" class="form-control" name="descricao" placeholder="Descrição" /><br />
        <input type="text" class="form-control" name="unidade" placeholder="Unidade" /><br />
        <select class="form-control" name="grupo">
        {% for grupo in grupos %}
            <option value="{{grupo.id}}">{{grupo}}</option>
        {% endfor %}
        </select><br />
        <button type="submit" class="btn btn-default">Enviar</button>
    </form>
</div>
{%endblock%}

project/templates/materiais/detalhe.html
{% extends "materiais/materiais_base.html" %}

{%block content %}
	<h3>{{material}}</h3>
	<span>Codigo: {{material.codigo}}</span>
	<br/>
	<span>Descricao: {{material.descricao}}</span>
	<br/>
	<span>Grupo: {{material.grupo}}</span>
{% endblock %}

project/templates/materiais/materiais_base.html
{% extends "base.html" %}

{%block main_content %}
<h1>Materiais</h1>
<div class="row">
    <div class="col-lg-2">
        <ul class="nav nav-stacked">
            <li><a href="{% url "materiais:index" %}">Lista</a></li>
            <li><a href="{% url "materiais:adicionar_plain" %}">Adicionar plain</a></li>
            <li><a href="{% url "materiais:adicionar_class" %}">Adicionar class</a></li>
            <li><a href="{% url "materiais:adicionar_model" %}">Adicionar model</a></li>
        </ul>
    </div>
    <div class="col-lg-10">{%block content%}{%endblock%}</div>
</div>
{%endblock%}

project/templates/materiais/material_list.html
{% extends "materiais/materiais_base.html" %}

{%block content %}
	{% if not material_list %}
		<p>Sem materiais para exibir.</p>
	{%else%}
        {% include "_pagination.html" %}
		<ul>
		{% for m in material_list %}
		    <li><a href="{% url "materiais:detalhe" m.id %}">{{m.descricao}}</a></li>
		{%endfor%}
		</ul>
        {% include "_pagination.html" %}
	{%endif%}
{%endblock%}